import { Experience } from "@/interfaces/experience";

export const experience: Experience[] = [
  {
    role: "IT Student Developer",
    company: "Information Security Office, CSUF",
    start: "May 2024",
    end: "Present",
    description: [
      "Built and deployed a production-grade <strong>RAG-powered AI dashboard</strong> using <strong>LangChain</strong>, <strong>FastAPI</strong>, <strong>NextJS</strong>, <strong>LLMs (AWS Bedrock)</strong>, and <strong>Neo4J</strong> to analyze infrastructure data and generate contextual insights via retrieval-based workflows.",
      "Designed an <strong>AWS IAM reporting tool</strong> that analyzed <strong>100+ IAM roles</strong> across multiple AWS accounts and applied <strong>Amazon Bedrock (LLMs)</strong> to translate policy data into actionable summaries, collaborating with security teams to improve visibility.",
      "Automated monthly <strong>AWS Security Hub</strong> reporting using <strong>EventBridge</strong> and <strong>Lambda</strong>, saving 4-5 hours of manual work and boosting critical issue visibility by 70%.",
      "Designed and implemented an <strong>AWS Inspector</strong> automated reporting pipeline using <strong>Step Functions, Lambda, DynamoDB, S3, EventBridge, and SES</strong>, reducing manual effort and improving visibility across 50+ servers.",
      "Redesigned and developed the <strong><a target='_blank' style='text-decoration: underline' title='CSUF ISO website' href='https://www.fullerton.edu/it/services/iso/'>CSUF ISO website</a></strong> in <strong>Omni CMS V5</strong>, modernizing its architecture and improving usability and maintainability.",
      "Analyzed <strong>CISA vulnerability reports</strong> for 20+ applications, identifying 50+ critical issues and driving a 40% reduction in vulnerabilities within 3 months.",
      "Built <strong>Python automation scripts</strong> to audit DUO authentication on 500+ servers, improving access control audit readiness.",
    ],
    technologies: [
      "Python",
      "TypeScript",
      "LangChain",
      "FastAPI",
      "NextJS",
      "AWS Bedrock",
      "Neo4J",
      "AWS",
      "Omni CMS",
      "Security",
    ],
  },
  {
    role: "Founding Engineer",
    company: "BoltAbacus",
    start: "Jul 2023",
    end: "Nov 2023",
    description: [
      "Led <strong>0 to 1 development</strong> of a full-stack <strong>e-learning platform</strong> for 700+ global users using <strong>ReactJS</strong>, <strong>Tailwind</strong>, <strong>Django</strong>, and <strong>PostgreSQL</strong>.",
      "Implemented <strong>scalable backend architecture</strong> with optimized database queries, indexing strategies, and access-control layers to ensure predictable performance under growing user load.",
      "Improved system response time by 50% by offloading email processing to <strong>AWS SNS</strong>, <strong>SQS</strong>, and <strong>Lambda</strong>.",
      "Implemented <strong>REST APIs</strong> with <strong>JWT authentication</strong> and role-based access, ensuring privacy and secure sessions.",
      "Owned cloud deployment and release engineering using <strong>S3</strong>, <strong>CloudFront</strong>, <strong>Route53</strong>, and <strong>AWS Amplify</strong>, establishing multi-env CI/CD pipelines for faster QA cycles.",
      "<a target='_blank' style='text-decoration: underline' title='BoltAbacus website' href='https://boltabacus.com/'><strong>View Website</strong></a>",
    ],
    technologies: ["ReactJS", "Tailwind", "Django", "PostgreSQL", "AWS"],
  },
  {
    role: "Software Development Engineer Intern",
    company: "Amazon",
    start: "Jan 2023",
    end: "Jun 2023",
    description: [
      "Developed a <strong>cancellation reason tracking</strong> feature using <strong>Java Guice</strong>, storing data in <strong>DynamoDB</strong> & <strong>Elasticsearch</strong>, publishing metrics to <strong>CloudWatch</strong>.",
      "Built CI/CD pipelines using <strong>TypeScript AWS CDK</strong> with reusable modules for backend services.",
      "Developed accessible frontend components using <strong>ReactJS</strong>, <strong>Redux</strong>, and <strong>RxJS</strong> for ARIA-compliant interfaces.",
      "Provisioned cloud infrastructure with <strong>Dagger</strong>, <strong>Lambda</strong>, <strong>SNS</strong>, <strong>SQS</strong>, <strong>Step Functions</strong>, <strong>API Gateway</strong>, and <strong>DynamoDB</strong>.",
      "Improved service quality through <strong>Jest</strong> and <strong>JUnit</strong> test coverage and gained deep debugging skills via on-call shadowing.",
    ],
    technologies: [
      "Java",
      "Google Guice",
      "Dagger",
      "ReactJS",
      "TypeScript",
      "AWS",
      "RxJS",
      "Redux",
    ],
  },
];
