import type { Icon } from "@dev.icons/react";
import {
  Aws,
  CPlusplus,
  ClaudeCode,
  ClaudeIcon,
  CloudflareIcon,
  Css3Icon,
  CursorIcon,
  DjangoIcon,
  DockerIcon,
  Electron,
  ExpoIcon,
  FastapiIcon,
  GitIcon,
  GithubCopilot,
  GithubIcon,
  Go,
  GoogleCloud,
  Graphql,
  Html5,
  Java,
  Javascript,
  Jest,
  KafkaIcon,
  Kubernetes,
  Langchain,
  LanggraphIcon,
  Langsmith,
  Maven,
  MicrosoftAzure,
  MongodbIcon,
  MysqlIcon,
  NeonIcon,
  Nestjs,
  NextjsIcon,
  Nginx,
  NodejsIcon,
  OllamaIcon,
  OpenaiIcon,
  OpentelemetryIcon,
  Oracle,
  PineconeIcon,
  Postgresql,
  Prisma,
  Prometheus,
  Puppeteer,
  Python,
  RedisIcon,
  Solidity,
  SpringIcon,
  SupabaseIcon,
  Swift,
  TailwindIcon,
  TerraformIcon,
  TypescriptIcon,
  Vite,
  _React,
} from "@dev.icons/react";

export interface Skill {
  name: string;
  Icon: Icon;
}

export interface SkillGroup {
  category: string;
  skills: Skill[];
}

export const skillGroups: SkillGroup[] = [
  {
    category: "Languages",
    skills: [
      { name: "TypeScript", Icon: TypescriptIcon },
      { name: "JavaScript", Icon: Javascript },
      { name: "Python", Icon: Python },
      { name: "Java", Icon: Java },
      { name: "C++", Icon: CPlusplus },
      { name: "GoLang", Icon: Go },
      { name: "Swift", Icon: Swift },
      { name: "Solidity", Icon: Solidity },
    ],
  },
  {
    category: "Frontend & Frameworks",
    skills: [
      { name: "React.js", Icon: _React },
      { name: "Next.js", Icon: NextjsIcon },
      { name: "Node.js", Icon: NodejsIcon },
      { name: "Tailwind CSS", Icon: TailwindIcon },
      { name: "HTML", Icon: Html5 },
      { name: "CSS", Icon: Css3Icon },
      { name: "Vite", Icon: Vite },
      { name: "Expo", Icon: ExpoIcon },
      { name: "Electron", Icon: Electron },
      { name: "Spring", Icon: SpringIcon },
      { name: "Django", Icon: DjangoIcon },
      { name: "FastAPI", Icon: FastapiIcon },
      { name: "NestJS", Icon: Nestjs },
      { name: "GraphQL", Icon: Graphql },
    ],
  },
  {
    category: "Cloud, DevOps & Tooling",
    skills: [
      { name: "AWS", Icon: Aws },
      { name: "GCP", Icon: GoogleCloud },
      { name: "Azure", Icon: MicrosoftAzure },
      { name: "Cloudflare", Icon: CloudflareIcon },
      { name: "Docker", Icon: DockerIcon },
      { name: "Kubernetes", Icon: Kubernetes },
      { name: "Terraform", Icon: TerraformIcon },
      { name: "Nginx", Icon: Nginx },
      { name: "Git", Icon: GitIcon },
      { name: "GitHub", Icon: GithubIcon },
      { name: "Kafka", Icon: KafkaIcon },
      { name: "Puppeteer", Icon: Puppeteer },
      { name: "Jest", Icon: Jest },
      { name: "Maven", Icon: Maven },
      { name: "OpenTelemetry", Icon: OpentelemetryIcon },
      { name: "Prometheus", Icon: Prometheus },
    ],
  },
  {
    category: "Databases",
    skills: [
      { name: "Postgres", Icon: Postgresql },
      { name: "MySQL", Icon: MysqlIcon },
      { name: "MongoDB", Icon: MongodbIcon },
      { name: "Redis", Icon: RedisIcon },
      { name: "Oracle", Icon: Oracle },
      { name: "Neon", Icon: NeonIcon },
      { name: "Supabase", Icon: SupabaseIcon },
      { name: "Prisma", Icon: Prisma },
      { name: "Pinecone", Icon: PineconeIcon },
    ],
  },
  {
    category: "AI & LLM Tooling",
    skills: [
      { name: "LangChain", Icon: Langchain },
      { name: "LangGraph", Icon: LanggraphIcon },
      { name: "LangSmith", Icon: Langsmith },
      { name: "OpenAI", Icon: OpenaiIcon },
      { name: "Ollama", Icon: OllamaIcon },
      { name: "Claude", Icon: ClaudeIcon },
      { name: "Claude Code", Icon: ClaudeCode },
      { name: "Cursor", Icon: CursorIcon },
      { name: "GitHub Copilot", Icon: GithubCopilot },
    ],
  },
];

export const skills: Skill[] = skillGroups.flatMap((group) => group.skills);
